application:
  name: Referencies-spring-cloud-config-server
  version: 0.0.2-SNAPSHOT

server:
  port: 3156
  address: 0.0.0.0

spring:
  application:
    name: RSCCS
  cloud:
    config:
      server.git.uri: "file://disk/learnspace/_tmp/config-repo"
  databases:
    postgres:
      infodb:
        driverClassName: "org.postgresql.Driver"
        jdbcUrl:  "jdbc:postgresql://93.180.54.197:5432/infodb"
        username: postgres
        password: a123456
        poolSize: 50
        initialSize: 50
        minIdle: 1
        maxIdle: 1
        maxActive: 20